stages:
  - build
  - deploy

sanity:
  stage: build
  image: alpine:3.19
  script:
    - echo "CI running"
  rules:
    - when: always

pages:
  stage: deploy
  image: alpine:3.19
  script:
    - mkdir -p public
    - cp -r softupakaran-clickable-slider-8085/* public/
  artifacts:
    paths:
      - public
  rules:
    - when: always
