services:
  backend:
    build: ./services/backend
    ports:
      - "4000:4000"
    env_file:
      - ./services/backend/.env.example
    volumes:
      - ./services/backend/data:/app/data
      - ./services/backend/uploads:/app/uploads
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

  frontend:
    build: ./services/frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
