version: '3'

services:
  jenkins:
    build:
      context: ../..
      dockerfile: ci/jenkins/Dockerfile
    image: softupakaran/jenkins-agent:latest
    container_name: softupakaran-jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  nginx:
    image: nginx:stable
    container_name: softupakaran-jenkins-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - jenkins

volumes:
  jenkins_home:
